### ISSUE TITLE
Add support to allow event bubbling.

### ISSUE THREAD

**Issue by techwraith** [OscarGodson/jKey#1]
If you bind the up/down keys to window, you lose page scroll capabilities, I think it would be a good idea to add support for event bubbling so the event still makes it up the chain.

You can do this by passing a "bubble" Boolean into the function.

e.g.

$(window).jkey("up", true, function(key){ //do stuff with the up key}

**Comment by OscarGodson** [comment]
Great idea. Ill work on this, or feel free to submit a pull request!

**Comment by tanelpuhu** [comment]
And maybe something similar to keep ability to enter text into form elements.

In sample.html : 'Type the letter "i" inside the box' :
If you press 'a', 'w' or try to move to left or right nothing happens, except that what was excepted from demo ;)

**Comment by OscarGodson** [comment]
I'm going to try to implement this today. Hopefully I can push something today also :)

**Comment by OscarGodson** [comment]
@Tanelpuhu Could you explain your issue more? If you focus on an input, as per browser defaults, you wont be able to scroll left, right, up, down. You could implement your own scrolling though with a jkey event with up and down to scrollTop() in the callback. 

For example: http://www.w3schools.com/TAGS/tag_input.asp 
Then focus on the search field and try to scroll.

A and W _shouldnt_ do anything in the input field although I noticed a different issue where it does trigger events even tho it shouldnt when window has events binded and your focused on a child DOM element.

**Comment by techwraith** [comment]
I think @Tanelpuhu was saying that the hotkeys end up hijacking the input. So, if you wanted to type "This" in the input, but the "s" was bound to the window, you would only be able to type "Thi".

**Comment by tanelpuhu** [comment]
Yeah, just that. And I also tried to select text as i normally do, with  Shift(+Ctrl)+Left/Right (Ctrl for per word).

Once-upon time I have also done something like this:
....
            $(document).bind('keypress',function(e){
                target = e.target.type || 'other';
                if(target != 'text' && target != 'submit'){
                    if(e.which==32){
                        playSong();
....

**Comment by OscarGodson** [comment]
Awh, I see yes. I've just implemented the event bubbling boolean param which I've done some quick testing and it works. I'll throw it up in a bit. I haven't yet got the full bind/unbind working though so that you can "undo" a binding though. I'll put an example of the event bubbling param upon pushing as well.

**Comment by OscarGodson** [comment]
Closing this now. Bubbling now (should) work. Feel free to re-open if something is broken!
