### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by rauschma** [OscarGodson/jKey#21]
One doesn’t see a page when going to http://oscargodson.com/labs/jkey/

**Comment by OscarGodson** [comment]
Awh, yes, moved my site. I just pushed a gh-pages branch instead:

http://oscargodson.github.com/jKey/

**Comment by rauschma** [comment]
Got it. You only need to update the link in README.md then.

**Comment by OscarGodson** [comment]
Right, good catch. Fixed!

**Comment by rauschma** [comment]
Thanks for this library!

In use here: https://github.com/rauschma/jsrepl

On Jul 10, 2012, at 17:12 , Oscar Godson wrote:

> Right, good catch. Fixed!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/OscarGodson/jKey/issues/21#issuecomment-6878407

## 

Dr. Axel Rauschmayer
axel@rauschma.de

home: rauschma.de
twitter: twitter.com/rauschma
blog: 2ality.com
