### ISSUE TITLE
Internet Explorer trouble

### ISSUE THREAD

**Issue by BraveNewMath** [OscarGodson/jKey#7]
I was using it to detect if a letter d is clicked like so

 $(window).jkey('d',true,function(){alert('you clicked d');});

but it doesn't work in ie.

**Comment by OscarGodson** [comment]
Can you try without an alert? Because of how alerts "blur" the keyup event it might be causing issues. This is why the jKey sample page is built using console logs.

**Comment by BraveNewMath** [comment]
I also tested your sample code, key events against $(window) appear to fail.  

To be specific, I am using IE8 and the following combos also fail:
$(window).jkey('y+u',function(){
    jkey.log('You pressed y and u!');
});

$(window).jkey('w, up',function(){
    jkey.log('You pressed either w, or up!');
});

**Comment by OscarGodson** [comment]
Alright thanks! I'll try to get that worked out tonight. If you wanna take a stab at it feel free to send me a pull request.

**Comment by kalahari** [comment]
Any word on this issue? I get no joy as well when trying to use window level events in IE8. No errors come through in the developer console for what that's worth.

**Comment by kalahari** [comment]
I found a work-around from this page: http://jqueryfordesigners.com/adding-keyboard-navigation/

if I use: 

jQuery(document.documentElement).jkey('tab', myFunction);

instead of:

jQuery(window).jkey('tab', myFunction);

everything is good.

**Comment by OscarGodson** [comment]
Sorry, too many projects too little time :( if you know how to fix it you can send a pull request. Ill also try looking into this ASAP.

**Comment by BraveNewMath** [comment]
i have the same problem of time constraints here too.  I have exams coming
up... but if I have time in the summer time, i will look more into fixing
it.

Best Regards.

**Comment by OscarGodson** [comment]
I figured out the issue (i think). IE doesnt support key downs on the window object. In the next update ill make it so if a user selects the window it'll convert it to $(document). for example:

``` javascript
//This
$(window).jkey('a',function(){});

//would be converted by me to:
$(document).jkey('a',function(){});
```
